export const VIP_TABLE_HEADER = [
  "ลำดับ",
  "เลขทะเบียนรถ",
  "จังหวัด",
  "ชื่อ-นามสกุล",
  "อีเมล",
  "หมายเลขโทรศัพท์",
  "แก้ไขข้อมูล",
];

export const MOCK_VIP_TABLE = [
  {
    id: 1,
    licensePlate: "1กก 1234",
    province: "กรุงเทพมหานคร",
    name: "สมชาย ใจดี",
    email: "somchai@gmail.com",
    phoneNumber: "081-123-4567",
    edit: "แก้ไข",
  },
  {
    id: 2,
    licensePlate: "2ขข 5678",
    province: "กรุงเทพมหานคร",
    name: "สมหญิง แสนสวย",
    email: "somying@gmail.com",
    phoneNumber: "086-987-6543",
    edit: "แก้ไข",
  },
  {
    id: 3,
    licensePlate: "3คค 9101",
    province: "เชียงใหม่",
    name: "วิชัย เรืองแสง",
    email: "vichai@gmail.com",
    phoneNumber: "089-555-1234",
    edit: "แก้ไข",
  },
  {
    id: 4,
    licensePlate: "4งง 2345",
    province: "นครปฐม",
    name: "มานะ ทรงชัย",
    email: "mana@gmail.com",
    phoneNumber: "084-321-9876",
    edit: "แก้ไข",
  },
  {
    id: 5,
    licensePlate: "5จจ 6789",
    province: "นครราชสีมา",
    name: "จิตรา แสนดี",
    email: "chittra@gmail.com",
    phoneNumber: "082-654-7890",
    edit: "แก้ไข",
  },
  {
    id: 6,
    licensePlate: "6ฉฉ 1012",
    province: "ภูเก็ต",
    name: "ประยุทธ์ ปลอดภัย",
    email: "prayoot@gmail.com",
    phoneNumber: "085-123-6547",
    edit: "แก้ไข",
  },
  {
    id: 7,
    licensePlate: "7ชช 2345",
    province: "กรุงเทพมหานคร",
    name: "อนุชา ยอดเยี่ยม",
    email: "anucha@gmail.com",
    phoneNumber: "083-654-9870",
    edit: "แก้ไข",
  },
  {
    id: 8,
    licensePlate: "8ซซ 4567",
    name: "จริยา อ่อนหวาน",
    email: "jariya@gmail.com",
    province: "เชียงราย",
    phoneNumber: "087-234-6789",
    edit: "แก้ไข",
  },
  {
    id: 9,
    licensePlate: "9ญญ 7890",
    province: "ชลบุรี",
    name: "พิมพ์ใจ รักดี",
    email: "pimmy@gmail.com",
    phoneNumber: "089-123-4321",
    edit: "แก้ไข",
  },
  {
    id: 10,
    licensePlate: "10ฎฎ 1234",
    province: "นครนายก",
    name: "สุนทร ขันติ",
    email: "sunthorn@gmail.com",
    phoneNumber: "082-789-1234",
    edit: "แก้ไข",
  },
];

export const MOCK_DATA_API = {
  pageSize: 10,
  rows: 508,
};
